// Code generated by hertz generator.

package example

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	example "go_api_service/biz/model/hello/example"
)

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(example.HelloResp)

	message := new(example.Common)

	data := make([]*example.Data, 0)
	message.Message = "成功"
	message.Code = 0

	resp.Message = message
	resp.Data = data
	c.JSON(consts.StatusOK, resp)
}
